name: nutripuntos_app
description: Nutripuntos App con Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  flutter_launcher_icons: ^0.6.1  
  image_picker: ^0.6.7+2
  image_crop: ^0.3.1
  url_launcher: ^5.0.2
  date_utils: ^0.1.0
  path_provider: ^1.4.0
  path_provider_macos: ^0.0.4
  expandable: ^3.0.0+1
  intl: ^0.16.0
  sqflite: ^1.0.0
  auto_size_text: ^2.1.0    
  device_info: ^0.4.2+6
  charts_flutter: ^0.8.1
  #flutter_charts: ^0.1.10
  flutter_slidable: "^0.5.4"
  #syncfusion_flutter_charts: ^18.2.55 #^1.0.0-beta.3
  flutter_plugin_pdf_viewer: ^1.0.7
  fl_chart: ^0.10.1
  #camera: 0.5.4+1
  

flutter_icons:
  image_path: "assets/launchers/web_hi_res_512.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/fondo.jpg
    - assets/images/logo.png
    - assets/images/photo.jpg
    - assets/icons/recurso_1.png   # puntos logo
    - assets/icons/recurso_2.png   # icono médico hombre
    - assets/icons/recurso_3.png   # icono médico mujer
    - assets/icons/recurso_4.png   # fondo foto usuario
    - assets/icons/recurso_5.png   # nuevas recetas
    - assets/icons/recurso_6.png   # metas
    - assets/icons/recurso_7.png   # nuevo plan
    - assets/icons/recurso_8.png   # restaurantes zona
    - assets/icons/recurso_9.png   # menu restaurantes
    - assets/icons/recurso_10.png  # menu nutriochat
    - assets/icons/recurso_11.png  # menu plan
    - assets/icons/recurso_12.png  # menu agenda
    - assets/icons/recurso_13.png  # menu progreso
    - assets/icons/recurso_14.png  # menu recetas
    - assets/icons/Recurso_21.png
    - assets/icons/Recurso_22.png
    - assets/icons/Recurso_23.png
    - assets/icons/Recurso_24.png
    - assets/icons/Recurso_25.png  # menu recetas
    - assets/icons/Recurso_26.png  # menu recetas
    - assets/icons/Recurso_27.png  
    - assets/icons/ejes.png  
    - assets/icons/barra_graphic.png  
    - assets/images/gr_peso.png
    - assets/images/gr_grasa.png
    - assets/images/gr_metas.png
    - assets/images/gr_recetas.png
    - assets/images/gr_restaurantes.png    
    - assets/icons/tiempo_desayuno.png
    - assets/icons/tiempo_bebida.png
    - assets/icons/tiempo_comida.png
    - assets/icons/tiempo_snack.png
    - assets/icons/tiempo_cena.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
